// src/config.ts
import {
  SUPABASE_URL,
  SUPABASE_ANON_KEY,
  CALORIE_MAMA_API_KEY,
  CALORIE_MAMA_API_URL,
} from '@env';

export const SUPABASE_URL_CONFIG = SUPABASE_URL;
export const SUPABASE_ANON_CONFIG = SUPABASE_ANON_KEY;

// Calorie Mama Food Recognition API
export const CALORIE_MAMA_API_KEY_CONFIG = CALORIE_MAMA_API_KEY;
export const CALORIE_MAMA_API_URL_CONFIG = CALORIE_MAMA_API_URL;
