// src/config.ts
export const SUPABASE_URL = "https://pgkiwkrucbthyjrweccl.supabase.co";
export const SUPABASE_ANON = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBna2l3a3J1Y2J0aHlqcndlY2NsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1Njk1NjgsImV4cCI6MjA3NDE0NTU2OH0.Pu-fLGl9gI9-FFF3OMQWfRNBmBHFOp7pVvUVNJVHpEA";
